import React, {useState, useEffect, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Plane, ArrowLeftRight, ChevronDown, Check, Download, X, Search, RotateCcw, Wallet, LoaderCircle} from 'lucide-react';
import {QRCodeSVG} from 'qrcode.react';
import './styles.css';
import {passTheme} from '../shared/theme.js';
import {createApiClient} from './api-client.js';
const api=createApiClient({base:import.meta.env.VITE_API_BASE||'',staticHosting:import.meta.env.VITE_STATIC_HOSTING==='true'});
const assetBase=import.meta.env.BASE_URL;

const templates=[
 {id:'united',name:'United Airlines',short:'United',color:'#083ca6',accent:'#e9ed9a',prefix:'UA',tag:'Classic blue'},
 {id:'emirates',name:'Emirates',short:'Emirates',color:'#b82331',accent:'#f4dfbe',prefix:'EK',tag:'Signature red'},
 {id:'etihad',name:'Etihad Airways',short:'Etihad',color:'#202b2b',accent:'#d6b46d',prefix:'EY',tag:'Modern luxury'},
 {id:'klm',name:'KLM',short:'KLM',color:'#0086bd',accent:'#dcf6ff',prefix:'KL',tag:'Sky blue'},
 {id:'singapore',name:'Singapore Airlines',short:'Singapore',color:'#092e61',accent:'#ffb24a',prefix:'SQ',tag:'Midnight & gold'},
];
const defaults={template:'united',name:'Ryan Ariano',cabin:'First',from:{code:'DEN',city:'Denver',name:'Denver International Airport',country:'US'},to:{code:'JAC',city:'Jackson Hole',name:'Jackson Hole Airport',country:'US'},date:'2026-10-15',boardingTime:'19:25',flight:'UA 1846',seat:'11A',gate:'B82',group:'2',barcode:''};
function AirportSearch({label,value,onChange,airports}){
 const [query,setQuery]=useState(''),[open,setOpen]=useState(false),[active,setActive]=useState(0);const ref=useRef(null);const listId=React.useId();
 useEffect(()=>{function close(e){if(!ref.current?.contains(e.target))setOpen(false);}document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close);},[]);
 const q=query.trim().toLowerCase();
 const results=(q?airports.filter(a=>`${a.code} ${a.city} ${a.name} ${a.country}`.toLowerCase().includes(q)).sort((a,b)=>(b.code.toLowerCase()===q)-(a.code.toLowerCase()===q)):['CPH','LHR','JFK','DXB','SIN','AMS','DEN','JAC'].map(c=>airports.find(a=>a.code===c)).filter(Boolean)).slice(0,6);
 function select(a){onChange(a);setQuery('');setOpen(false);}
 return <div className="airport-field" ref={ref}><label htmlFor={listId}>{label}</label><div className={`airport-input ${open?'focused':''}`}><div className="airport-icon"><Plane size={17} className={label==='Arrival airport'?'arrival':''}/></div><div className="airport-text"><input id={listId} role="combobox" aria-expanded={open} aria-controls={`${listId}-results`} aria-autocomplete="list" aria-activedescendant={open&&results.length?`${listId}-${active}`:undefined} value={open?query:`${value.city} (${value.code})`} placeholder="Search city, airport or IATA" onFocus={()=>{setOpen(true);setQuery('');setActive(0);}} onBlur={e=>{if(!ref.current?.contains(e.relatedTarget))setOpen(false);}} onChange={e=>{setQuery(e.target.value);setActive(0);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(i=>Math.min(i+1,results.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(i-1,0));}if(e.key==='Enter'&&open){e.preventDefault();if(results[active])select(results[active]);}if(e.key==='Escape')setOpen(false);}}/><span>{open?'Find your airport':value.name}</span></div><ChevronDown size={15}/></div>{open&&<div className="airport-results" id={`${listId}-results`} role="listbox"><div className="search-caption"><Search size={12}/>{q?'SEARCH RESULTS':'POPULAR AIRPORTS'}</div>{results.length?results.map((a,i)=><button type="button" id={`${listId}-${i}`} key={a.code} role="option" aria-selected={i===active} className={i===active?'active':''} onMouseDown={e=>e.preventDefault()} onClick={()=>select(a)}><strong>{a.code}</strong><span>{a.city}<small>{a.name}</small></span>{a.code===value.code&&<Check size={15}/>}</button>):<p>{airports.length?'No airports found. Try a city or IATA code.':'Loading airport directory…'}</p>}</div>}</div>
}
function Field({label,id,children,...props}){return <div className="field"><label htmlFor={id}>{label}</label>{children||<input id={id} {...props}/>}</div>}
function AirlineLogo({id,...props}){return <img src={`${assetBase}logos/${id==='emirates'?'emirates-logo':id}.png`} alt={`${templates.find(t=>t.id===id).name} logo`} {...props}/>}
function ColorPicker({value,defaultColor,onChange}){
 const customRef=useRef(null);
 const presets=[{name:'Airline default',color:defaultColor},...[
  {name:'Black',color:'#202020'},{name:'Navy',color:'#092e61'},{name:'Blue',color:'#083ca6'},
  {name:'Sky blue',color:'#0086bd'},{name:'Red',color:'#b82331'},{name:'Green',color:'#21583f'},
  {name:'Gold',color:'#c79a3c'},{name:'White',color:'#f5f5f5'},
 ].filter(c=>c.color.toLowerCase()!==defaultColor.toLowerCase())];
 return <div className="color-picker"><div className="color-picker-heading"><span>Pass color</span><button type="button" className="color-default" onClick={()=>onChange(defaultColor)}>Airline default</button></div><div className="color-swatches" role="group" aria-label="Choose pass color">{presets.map(c=><button type="button" key={c.name} className={`color-swatch ${value.toLowerCase()===c.color.toLowerCase()?'selected':''}`} style={{'--swatch-color':c.color}} title={c.name} aria-label={c.name} aria-pressed={value.toLowerCase()===c.color.toLowerCase()} onClick={()=>onChange(c.color)}><span/></button>)}<button type="button" className="custom-color" onClick={()=>customRef.current?.click()}><span style={{background:value}}/>Custom</button><input ref={customRef} className="custom-color-input" type="color" value={value} onChange={e=>onChange(e.target.value)} aria-label="Custom pass color" tabIndex={-1}/></div></div>
}
function PassPreview({pass,back}){
 const t=templates.find(t=>t.id===pass.template);const theme=passTheme(t,pass.color);const time=pass.boardingTime?new Date(`2000-01-01T${pass.boardingTime}:00`).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}):'—';
 const date=new Date(pass.date+'T12:00:00');const displayDate=Number.isNaN(date.getTime())?'—':date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
 const barcode=pass.barcode||`PASSPORT-DEMO:${JSON.stringify({name:pass.name,from:pass.from.code,to:pass.to.code,date:pass.date,flight:pass.flight,seat:pass.seat})}`;
 return <div className={`boarding-pass ${back?'back':''}`} style={{'--pass-color':theme.background,'--pass-accent':theme.accent,'--pass-ink':theme.foreground,'--pass-muted':theme.darkInk?'#171717a8':'#ffffffa8','--logo-filter':t.id==='etihad'&&!theme.darkInk?'none':theme.darkInk?'brightness(0)':'brightness(0) invert(1)'}} aria-label="Live boarding pass preview">
 <div className="pass-top"><AirlineLogo id={t.id} className={`pass-logo ${t.id}`}/><div className="pass-gate"><small>GATE</small><span>{pass.gate||'—'}</span></div></div>
 {back?<div className="pass-back"><h3>Flight details</h3><p><small>PASSENGER</small>{pass.name||'—'}</p><p><small>TRAVEL DATE</small>{displayDate}</p><p><small>ROUTE</small>{pass.from.name}<br/>↓<br/>{pass.to.name}</p><p><small>CABIN CLASS</small>{pass.cabin}</p></div>:<>
 <div className="pass-route"><div><small>{pass.from.city.toUpperCase()}</small><strong>{pass.from.code}</strong></div><Plane size={34} fill="currentColor" strokeWidth={1}/><div><small>{pass.to.city.toUpperCase()}</small><strong>{pass.to.code}</strong></div></div>
 <div className="pass-flight"><div><small>BOARDS</small><span>{time}</span></div><div><small>FLIGHT</small><span>{pass.flight||'—'}</span></div><div><small>SEAT</small><span>{pass.seat||'—'}</span></div><div><small>GROUP</small><span>{pass.group||'—'}</span></div></div>
 <div className="pass-passenger"><small>PASSENGER</small><span>{pass.name.toUpperCase()||'YOUR NAME'}</span><div className="pass-cabin">{pass.cabin}<span>·</span>{displayDate}</div></div>
 <div className="pass-barcode"><div className="qr-frame"><QRCodeSVG value={barcode} size={164} level="M" marginSize={0}/></div></div>

 </>}
 </div>
}
function App(){
 const [pass,setPass]=useState(()=>{try{const v=JSON.parse(localStorage.getItem('passport-draft'));return v&&templates.some(t=>t.id===v.template)&&v.from?.code&&v.to?.code?{...defaults,...v,cabin:'First'}:defaults;}catch{return defaults;}});
 const [airports,setAirports]=useState([]),[exportOpen,setExportOpen]=useState(false),[back,setBack]=useState(false),[provider,setProvider]=useState(api.configured?'free':'unavailable'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const formRef=useRef(null),exportRef=useRef(null);const t=templates.find(t=>t.id===pass.template);
 useEffect(()=>{fetch(`${assetBase}airports.json`).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(setAirports).catch(()=>setNotice('Airport directory could not load. Refresh to try again.'));if(api.configured)api.status().then(d=>setProvider(d.provider||'free')).catch(()=>{});},[]);
 useEffect(()=>{try{localStorage.setItem('passport-draft',JSON.stringify(pass));}catch{}},[pass]);
 useEffect(()=>{if(!notice)return;const timeout=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timeout);},[notice]);
 useEffect(()=>{if(!exportOpen)return;const old=document.activeElement;const onKey=e=>{if(e.key==='Escape'){setExportOpen(false);}if(e.key==='Tab'){const nodes=exportRef.current?.querySelectorAll('button:not(:disabled),a[href],input,textarea');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',onKey);exportRef.current?.querySelector('button')?.focus();return()=>{document.removeEventListener('keydown',onKey);old?.focus();};},[exportOpen]);
 function update(key,value){setPass(p=>({...p,[key]:value}));setError('');}
 function selectTemplate(template){setPass(p=>({...p,template:template.id,cabin:'First',color:template.color,flight:template.prefix+p.flight.replace(/^[A-Z]{2}\s*/, ' ')}));}
 function openExport(){if(!formRef.current.reportValidity())return;if(pass.from.code===pass.to.code){setNotice('Choose two different airports.');return;}setError('');setExportOpen(true);}
 async function download(format){setBusy(format);setError('');try{const blob=await api.download(pass,format),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${pass.from.code}-${pass.to.code}-boarding-pass.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`${format==='zip'?'Template bundle':'Wallet pass'} downloaded.`);}catch(e){setError(e.message);}finally{setBusy('');}}
 function reset(){setPass({...defaults});setBack(false);setNotice('Pass reset.');}
 return <div className="app-shell">
 <div className="main-shell"><main>
 <div className="builder-grid"><section className="editor"><div className="section-heading"><span className="step">01</span><h2>Choose your template</h2><span className="muted-count">5 airline styles</span></div><div className="templates">{templates.map(template=><button key={template.id} type="button" className={`template ${pass.template===template.id?'selected':''}`} aria-label={`Use ${template.name} template`} onClick={()=>selectTemplate(template)} aria-pressed={pass.template===template.id}><div className={`template-art ${template.id}`} style={{'--template-color':template.color}}><AirlineLogo id={template.id}/>{pass.template===template.id&&<span className="template-check"><Check size={12}/></span>}</div><strong>{template.short}</strong></button>)}</div>
 <div className="form-card"><div className="section-heading"><span className="step">02</span><h2>Make it yours</h2></div><form ref={formRef} onSubmit={e=>{e.preventDefault();openExport();}}><div className="form-section-title">PASSENGER DETAILS</div><div className="passenger-fields"><Field label="Passenger name" id="name" value={pass.name} placeholder="As shown on your passport" maxLength={80} required onChange={e=>update('name',e.target.value)}/><Field label="Cabin class" id="cabin"><div className="select-wrap"><select id="cabin" value={pass.cabin} onChange={e=>update('cabin',e.target.value)}>{['Economy','Premium Economy','Business','First'].map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={15}/></div></Field></div>
 <div className="form-divider"/><div className="form-section-title">YOUR JOURNEY</div><div className="route-fields"><AirportSearch label="Departure airport" value={pass.from} onChange={v=>update('from',v)} airports={airports}/><button type="button" className="swap" title="Swap airports" aria-label="Swap departure and arrival airports" onClick={()=>setPass(p=>({...p,from:p.to,to:p.from}))}><ArrowLeftRight size={16}/></button><AirportSearch label="Arrival airport" value={pass.to} onChange={v=>update('to',v)} airports={airports}/></div><div className="two-fields"><Field label="Travel date" id="date" type="date" value={pass.date} required onChange={e=>update('date',e.target.value)}/><Field label="Boarding time" id="time" type="time" value={pass.boardingTime} required onChange={e=>update('boardingTime',e.target.value)}/></div><div className="four-fields"><Field label="Flight number" id="flight" value={pass.flight} maxLength={12} required onChange={e=>update('flight',e.target.value.toUpperCase())}/><Field label="Seat" id="seat" value={pass.seat} maxLength={6} required onChange={e=>update('seat',e.target.value.toUpperCase())}/><Field label="Gate" id="gate" value={pass.gate} maxLength={8} required onChange={e=>update('gate',e.target.value.toUpperCase())}/><Field label="Group" id="group" value={pass.group} maxLength={4} required onChange={e=>update('group',e.target.value)}/></div><div className="form-footer"><button type="button" onClick={reset}><RotateCcw size={13}/>Reset</button></div></form></div>
 <div className="export-strip"><button className="primary-button" onClick={openExport}><Download size={16}/>Download pass</button></div></section>
 <aside className="preview-panel"><div className="preview-heading"><div className="preview-tabs" role="group" aria-label="Preview side"><button className={!back?'active':''} aria-pressed={!back} onClick={()=>setBack(false)}>Front</button><button className={back?'active':''} aria-pressed={back} onClick={()=>setBack(true)}>Back</button></div></div><div className="preview-canvas"><PassPreview pass={pass} back={back}/></div><ColorPicker value={pass.color||t.color} defaultColor={t.color} onChange={value=>update('color',value)}/></aside></div>
 </main></div>
 {notice&&<div className="toast" role="status"><Check size={17}/>{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss message"><X size={14}/></button></div>}
 {exportOpen&&<div className="modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setExportOpen(false);}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title" ref={exportRef}><button className="modal-close" disabled={!!busy} onClick={()=>setExportOpen(false)} aria-label="Close dialog"><X size={19}/></button><h2 id="dialog-title">Download pass</h2><p>{t.name} · {pass.from.code} → {pass.to.code}<br/>{pass.name} · {pass.cabin}</p>{provider!=='unavailable'&&<div className="signing-state ready"><span/>{provider==='local'?'Signed with your certificate':'Free signing · up to 30 passes per day'}</div>}{provider==='free'&&<p className="modal-note">Your pass details and logo are sent to WalletMCPPass for signing.</p>}<button disabled={!!busy} className="primary-button full" onClick={()=>download('pkpass')}>{busy==='pkpass'?<LoaderCircle size={17} className="spin"/>:<Wallet size={17}/>}Download .pkpass</button><div className="export-separator"><span>TEMPLATE BUNDLE</span></div><button className="outline-button full" disabled={!!busy} onClick={()=>download('zip')}>{busy==='zip'?<LoaderCircle size={17} className="spin"/>:<Download size={17}/>}Download template ZIP</button><details className="barcode-option"><summary>Use your own barcode text</summary><label htmlFor="barcode">Barcode payload</label><textarea id="barcode" maxLength={1000} disabled={!!busy} value={pass.barcode} onChange={e=>update('barcode',e.target.value)} placeholder="Paste an existing boarding pass barcode payload"/><small>Leave empty to generate a QR from your pass details.</small></details>{error&&<p className="error-message" role="alert">{error}</p>}</div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
