import React, {useState, useEffect, useRef, useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {Plane, ArrowLeftRight, ChevronDown, Check, Download, X, Search, RotateCcw, Wallet, LoaderCircle} from 'lucide-react';
import {QRCodeSVG} from 'qrcode.react';
import './styles.css';
import {passTheme} from '../shared/theme.js';
import {createApiClient} from './api-client.js';
import {createQuickBatch,normalizeBatchName} from '../shared/quick-batch.js';
import {collectBatch} from './batch-download.js';
const api=createApiClient({base:import.meta.env.VITE_API_BASE||'',staticHosting:import.meta.env.VITE_STATIC_HOSTING==='true'});
const assetBase=import.meta.env.BASE_URL;

const templates=[
 {id:'united',name:'United Airlines',short:'United',color:'#083ca6',accent:'#e9ed9a',prefix:'UA',tag:'Classic blue'},
 {id:'emirates',name:'Emirates',short:'Emirates',color:'#b82331',accent:'#f4dfbe',prefix:'EK',tag:'Signature red'},
 {id:'etihad',name:'Etihad Airways',short:'Etihad',color:'#202b2b',accent:'#d6b46d',prefix:'EY',tag:'Modern luxury'},
 {id:'klm',name:'KLM',short:'KLM',color:'#0086bd',accent:'#dcf6ff',prefix:'KL',tag:'Sky blue'},
 {id:'singapore',name:'Singapore Airlines',short:'Singapore',color:'#092e61',accent:'#ffb24a',prefix:'SQ',tag:'Midnight & gold'},
];
const defaults={template:'united',name:'Ryan Ariano',cabin:'First',from:{code:'DEN',city:'Denver',name:'Denver International Airport',country:'US'},to:{code:'JAC',city:'Jackson Hole',name:'Jackson Hole Airport',country:'US'},date:'2026-10-15',boardingTime:'19:25',flight:'UA 1846',seat:'11A',gate:'B82',group:'2',barcode:''};
function AirportSearch({label,value,onChange,airports}){
 const [query,setQuery]=useState(''),[open,setOpen]=useState(false),[active,setActive]=useState(0);const ref=useRef(null);const listId=React.useId();
 useEffect(()=>{function close(e){if(!ref.current?.contains(e.target))setOpen(false);}document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close);},[]);
 const q=query.trim().toLowerCase();
 const results=(q?airports.filter(a=>`${a.code} ${a.city} ${a.name} ${a.country}`.toLowerCase().includes(q)).sort((a,b)=>(b.code.toLowerCase()===q)-(a.code.toLowerCase()===q)):['CPH','LHR','JFK','DXB','SIN','AMS','DEN','JAC'].map(c=>airports.find(a=>a.code===c)).filter(Boolean)).slice(0,6);
 function select(a){onChange(a);setQuery('');setOpen(false);}
 return <div className="airport-field" ref={ref}><label htmlFor={listId}>{label}</label><div className={`airport-input ${open?'focused':''}`}><div className="airport-icon"><Plane size={17} className={label==='Arrival airport'?'arrival':''}/></div><div className="airport-text"><input id={listId} role="combobox" aria-expanded={open} aria-controls={`${listId}-results`} aria-autocomplete="list" aria-activedescendant={open&&results.length?`${listId}-${active}`:undefined} value={open?query:`${value.city} (${value.code})`} placeholder="Search city, airport or IATA" onFocus={()=>{setOpen(true);setQuery('');setActive(0);}} onBlur={e=>{if(!ref.current?.contains(e.relatedTarget))setOpen(false);}} onChange={e=>{setQuery(e.target.value);setActive(0);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(i=>Math.min(i+1,results.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(i-1,0));}if(e.key==='Enter'&&open){e.preventDefault();if(results[active])select(results[active]);}if(e.key==='Escape')setOpen(false);}}/><span>{open?'Find your airport':value.name}</span></div><ChevronDown size={15}/></div>{open&&<div className="airport-results" id={`${listId}-results`} role="listbox"><div className="search-caption"><Search size={12}/>{q?'SEARCH RESULTS':'POPULAR AIRPORTS'}</div>{results.length?results.map((a,i)=><button type="button" id={`${listId}-${i}`} key={a.code} role="option" aria-selected={i===active} className={i===active?'active':''} onMouseDown={e=>e.preventDefault()} onClick={()=>select(a)}><strong>{a.code}</strong><span>{a.city}<small>{a.name}</small></span>{a.code===value.code&&<Check size={15}/>}</button>):<p>{airports.length?'No airports found. Try a city or IATA code.':'Loading airport directory…'}</p>}</div>}</div>
}
function Field({label,id,children,...props}){return <div className="field"><label htmlFor={id}>{label}</label>{children||<input id={id} {...props}/>}</div>}
function AirlineLogo({id,...props}){return <img src={`${assetBase}logos/${id==='emirates'?'emirates-logo':id}.png`} alt={`${templates.find(t=>t.id===id).name} logo`} {...props}/>}
function ColorPicker({value,defaultColor,onChange,disabled=false}){
 const customRef=useRef(null);
 const presets=[{name:'Airline default',color:defaultColor},...[
  {name:'Black',color:'#202020'},{name:'Navy',color:'#092e61'},{name:'Blue',color:'#083ca6'},
  {name:'Sky blue',color:'#0086bd'},{name:'Red',color:'#b82331'},{name:'Green',color:'#21583f'},
  {name:'Gold',color:'#c79a3c'},{name:'White',color:'#f5f5f5'},
 ].filter(c=>c.color.toLowerCase()!==defaultColor.toLowerCase())];
 return <div className="color-picker"><div className="color-picker-heading"><span>Pass color</span><button type="button" className="color-default" disabled={disabled} onClick={()=>onChange(defaultColor)}>Airline default</button></div><div className="color-swatches" role="group" aria-label="Choose pass color">{presets.map(c=><button type="button" key={c.name} disabled={disabled} className={`color-swatch ${value.toLowerCase()===c.color.toLowerCase()?'selected':''}`} style={{'--swatch-color':c.color}} title={c.name} aria-label={c.name} aria-pressed={value.toLowerCase()===c.color.toLowerCase()} onClick={()=>onChange(c.color)}><span/></button>)}<button type="button" className="custom-color" disabled={disabled} onClick={()=>customRef.current?.click()}><span style={{background:value}}/>Custom</button><input ref={customRef} className="custom-color-input" disabled={disabled} type="color" value={value} onChange={e=>onChange(e.target.value)} aria-label="Custom pass color" tabIndex={-1}/></div></div>
}
function PassPreview({pass,back}){
 const t=templates.find(t=>t.id===pass.template);const theme=passTheme(t,pass.color);const time=pass.boardingTime?new Date(`2000-01-01T${pass.boardingTime}:00`).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}):'—';
 const date=new Date(pass.date+'T12:00:00');const displayDate=Number.isNaN(date.getTime())?'—':date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
 const barcode=pass.barcode||`PASSPORT-DEMO:${JSON.stringify({name:pass.name,from:pass.from.code,to:pass.to.code,date:pass.date,flight:pass.flight,seat:pass.seat})}`;
 return <div className={`boarding-pass ${back?'back':''}`} style={{'--pass-color':theme.background,'--pass-accent':theme.accent,'--pass-ink':theme.foreground,'--pass-muted':theme.darkInk?'#171717a8':'#ffffffa8','--logo-filter':t.id==='etihad'&&!theme.darkInk?'none':theme.darkInk?'brightness(0)':'brightness(0) invert(1)'}} aria-label="Live boarding pass preview">
 <div className="pass-top"><AirlineLogo id={t.id} className={`pass-logo ${t.id}`}/><div className="pass-gate"><small>GATE</small><span>{pass.gate||'—'}</span></div></div>
 {back?<div className="pass-back"><h3>Flight details</h3><p><small>PASSENGER</small>{pass.name||'—'}</p><p><small>TRAVEL DATE</small>{displayDate}</p><p><small>ROUTE</small>{pass.from.name}<br/>↓<br/>{pass.to.name}</p><p><small>CABIN CLASS</small>{pass.cabin}</p></div>:<>
 <div className="pass-route"><div><small>{pass.from.city.toUpperCase()}</small><strong>{pass.from.code}</strong></div><Plane size={34} fill="currentColor" strokeWidth={1}/><div><small>{pass.to.city.toUpperCase()}</small><strong>{pass.to.code}</strong></div></div>
 <div className="pass-flight"><div><small>BOARDS</small><span>{time}</span></div><div><small>FLIGHT</small><span>{pass.flight||'—'}</span></div><div><small>SEAT</small><span>{pass.seat||'—'}</span></div><div><small>GROUP</small><span>{pass.group||'—'}</span></div></div>
 <div className="pass-passenger"><small>PASSENGER</small><span>{pass.name.toUpperCase()||'YOUR NAME'}</span><div className="pass-cabin">{pass.cabin}<span>·</span>{displayDate}</div></div>
 <div className="pass-barcode"><div className="qr-frame"><QRCodeSVG value={barcode} size={164} level="M" marginSize={0}/></div></div>

 </>}
 </div>
}
function PassDownloads({files,passes}){
 const [links,setLinks]=useState([]);
 useEffect(()=>{
  const downloads=files.map(file=>({...file,url:URL.createObjectURL(new Blob([file.bytes],{type:'application/vnd.apple.pkpass'}))}));
  setLinks(downloads);
  return()=>downloads.forEach(file=>URL.revokeObjectURL(file.url));
 },[files]);
 if(!links.length)return null;
 return <div className="pass-downloads"><p>Download each boarding pass separately.</p>{links.map(file=>{
  const pass=passes[file.index],airline=templates.find(t=>t.id===pass.template);
  return <a key={file.index} href={file.url} download={file.name}><Download size={15}/><span>{airline.short}<small>{pass.from.code} → {pass.to.code} · {pass.boardingTime}</small></span><span>.pkpass</span></a>;
 })}</div>;
}
function App(){
 const [pass,setPass]=useState(()=>{try{const v=JSON.parse(localStorage.getItem('passport-draft'));return v&&templates.some(t=>t.id===v.template)&&v.from?.code&&v.to?.code?{...defaults,...v,cabin:'First'}:defaults;}catch{return defaults;}});
 const [mode,setMode]=useState('custom'),[batchName,setBatchName]=useState(''),[batchCount,setBatchCount]=useState(3),[batchSeed,setBatchSeed]=useState(0),[previewIndex,setPreviewIndex]=useState(0),[batchFiles,setBatchFiles]=useState([]),[batchProgress,setBatchProgress]=useState(0);
 const [airports,setAirports]=useState([]),[exportOpen,setExportOpen]=useState(false),[back,setBack]=useState(false),[quota,setQuota]=useState(null),[provider,setProvider]=useState(api.configured?'free':'unavailable'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const formRef=useRef(null),quickRef=useRef(null),exportRef=useRef(null);const t=templates.find(t=>t.id===pass.template);
 const [batchColors,setBatchColors]=useState({});
 const batchPlan=useMemo(()=>airports.length?createQuickBatch({name:'LASTNAME/FIRSTNAME',count:batchCount,template:'united',mixedTemplates:true,airports}):[],[airports,batchCount,batchSeed]);
 const batchPasses=batchPlan.map(p=>({...p,color:batchColors[p.template],name:batchName.trim().toUpperCase()}));
 const previewPass=mode==='quick'?batchPasses[Math.min(previewIndex,batchPasses.length-1)]||{...pass,cabin:'First',name:batchName}:pass;
 const previewTemplate=templates.find(item=>item.id===previewPass.template);
 useEffect(()=>{setBatchFiles([]);setBatchProgress(0);setError('');},[batchPlan,batchName,batchColors,pass.template,pass.color]);
 useEffect(()=>{setPreviewIndex(0);},[batchPlan]);
 useEffect(()=>{fetch(`${assetBase}airports.json`).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(setAirports).catch(()=>setNotice('Airport directory could not load. Refresh to try again.'));refreshStatus();const interval=setInterval(refreshStatus,60000);const visible=()=>{if(!document.hidden)refreshStatus();};document.addEventListener('visibilitychange',visible);return()=>{clearInterval(interval);document.removeEventListener('visibilitychange',visible);};},[]);
 useEffect(()=>{try{localStorage.setItem('passport-draft',JSON.stringify(pass));}catch{}},[pass]);
 useEffect(()=>{if(!notice)return;const timeout=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timeout);},[notice]);
 useEffect(()=>{if(!exportOpen)return;const old=document.activeElement;const onKey=e=>{if(e.key==='Escape'&&!exportRef.current?.querySelector('.modal-close')?.disabled){setExportOpen(false);}if(e.key==='Tab'){const nodes=exportRef.current?.querySelectorAll('button:not(:disabled),a[href],input,textarea');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',onKey);exportRef.current?.querySelector('button')?.focus();return()=>{document.removeEventListener('keydown',onKey);old?.focus();};},[exportOpen]);
 useEffect(()=>{if(exportOpen)refreshStatus();},[exportOpen]);
 function refreshStatus(){if(api.configured)api.status().then(d=>{setProvider(d.provider||'free');setQuota(d.quota||null);}).catch(()=>{});}
 const quotaText=quota?`${quota.remaining} generations left today`:'Checking free pass allowance…';
 function update(key,value){if(busy)return;setPass(p=>({...p,[key]:value}));setError('');}
 function selectTemplate(template){if(busy)return;if(mode==='quick'){const index=batchPasses.findIndex(p=>p.template===template.id);if(index>=0){setPreviewIndex(index);return;}changeMode('custom');}setPass(p=>({...p,template:template.id,cabin:'First',color:template.color,flight:template.prefix+p.flight.replace(/^[A-Z]{2}\s*/, ' ')}));}
 function openExport(){if(mode==='quick'){if(!quickRef.current.reportValidity())return;try{normalizeBatchName(batchName);if(!batchPlan.length)throw new Error('The airport directory is still loading.');}catch(e){setNotice(e.message);return;}setError('');setExportOpen(true);return;}if(!formRef.current.reportValidity())return;if(pass.from.code===pass.to.code){setNotice('Choose two different airports.');return;}setError('');setExportOpen(true);}
 async function download(format){setBusy(format);setError('');try{const blob=await api.download(pass,format),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${pass.from.code}-${pass.to.code}-boarding-pass.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`${format==='zip'?'Template bundle':'Wallet pass'} downloaded.`);}catch(e){setError(e.message);}finally{setBusy('');refreshStatus();}}
 function saveBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 async function downloadQuickBatch(){
  let name;try{name=normalizeBatchName(batchName);}catch(e){setError(e.message);return;}
  const needed=batchCount-batchFiles.length;
  if(provider==='free'&&quota&&quota.remaining<needed){setError(`Only ${quota.remaining} generations left today. Choose fewer boarding passes.`);return;}
  setBusy('batch');setError('');
  try{
   const passes=batchPasses.map(p=>({...p,name}));
   const result=await collectBatch(passes,{download:api.download,completed:batchFiles,onProgress:done=>setBatchProgress(done),onFile:setBatchFiles});
   if(batchCount===1&&result.files.length)saveBlob(new Blob([result.files[0].bytes],{type:'application/vnd.apple.pkpass'}),result.files[0].name);
   if(result.error)setError(`${result.files.length} of ${batchCount} boarding passes ready to download. ${result.error.message}`);
   else setNotice(batchCount===1?'Boarding pass downloaded.':`${result.files.length} boarding passes ready. Tap each pass to download.`);
  }catch(e){setError(e.message);}finally{setBusy('');refreshStatus();}
 }
 function changeMode(value){setMode(value);setError('');setExportOpen(false);}
 function reset(){if(busy)return;if(mode==='quick'){setBatchName('');setBatchCount(3);setBatchColors({});setBatchSeed(s=>s+1);}else setPass({...defaults});setBack(false);setNotice('Pass reset.');}
 return <div className="app-shell">
 <div className="main-shell"><main>
 <div className="builder-grid"><section className="editor"><div className="section-heading"><span className="step">01</span><h2>Choose your template</h2><span className="muted-count">5 airline styles</span></div><div className="templates">{templates.map(template=><button key={template.id} type="button" className={`template ${previewPass.template===template.id?'selected':''}`} aria-label={`Use ${template.name} template`} disabled={!!busy} onClick={()=>selectTemplate(template)} aria-pressed={previewPass.template===template.id}><div className={`template-art ${template.id}`} style={{'--template-color':template.color}}><AirlineLogo id={template.id}/>{previewPass.template===template.id&&<span className="template-check"><Check size={12}/></span>}</div><strong>{template.short}</strong></button>)}</div>
 <div className="form-card"><div className="section-heading"><span className="step">02</span><h2>Make it yours</h2></div><div className="generation-mode" role="group" aria-label="Generation mode"><button type="button" disabled={!!busy} aria-pressed={mode==='quick'} onClick={()=>changeMode('quick')}>Quick generate</button><button type="button" disabled={!!busy} aria-pressed={mode==='custom'} onClick={()=>changeMode('custom')}>Custom pass</button></div>{mode==='quick'?<form ref={quickRef} onSubmit={e=>{e.preventDefault();openExport();}}><Field label="Passenger name" id="batch-name" value={batchName} placeholder="LASTNAME/FIRSTNAME" maxLength={80} pattern="[^/]+/[^/]+" required disabled={!!busy} onChange={e=>setBatchName(e.target.value.toUpperCase())}/><div className="batch-options"><div><span className="batch-label">Boarding passes</span><div className="batch-count" role="group" aria-label="Number of boarding passes">{[1,2,3,4,5].map(n=><button key={n} type="button" disabled={!!busy} aria-pressed={batchCount===n} onClick={()=>setBatchCount(n)}>{n}</button>)}</div></div><span className="first-class-label">First class</span></div><div className="batch-journeys" aria-label="Generated journeys">{batchPasses.map((p,i)=><button type="button" key={i} className={previewIndex===i?'selected':''} onClick={()=>setPreviewIndex(i)}><span className="journey-number">{String(i+1).padStart(2,'0')}</span><strong>{p.from.code}<span>→</span>{p.to.code}<small className="journey-airline">{templates.find(item=>item.id===p.template).short}</small></strong><span>{p.boardingTime}</span><span>{p.seat}</span></button>)}{!batchPasses.length&&<p>Loading airports…</p>}</div><div className="form-footer batch-footer"><button type="button" disabled={!!busy} onClick={()=>setBatchSeed(s=>s+1)}><RotateCcw size={13}/>Shuffle journeys</button><button type="button" disabled={!!busy} onClick={reset}>Reset</button></div></form>:<form ref={formRef} onSubmit={e=>{e.preventDefault();openExport();}}><div className="form-section-title">PASSENGER DETAILS</div><div className="passenger-fields"><Field label="Passenger name" id="name" value={pass.name} placeholder="As shown on your passport" maxLength={80} required onChange={e=>update('name',e.target.value)}/><Field label="Cabin class" id="cabin"><div className="select-wrap"><select id="cabin" value={pass.cabin} onChange={e=>update('cabin',e.target.value)}>{['Economy','Premium Economy','Business','First'].map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={15}/></div></Field></div>
 <div className="form-divider"/><div className="form-section-title">YOUR JOURNEY</div><div className="route-fields"><AirportSearch label="Departure airport" value={pass.from} onChange={v=>update('from',v)} airports={airports}/><button type="button" className="swap" title="Swap airports" aria-label="Swap departure and arrival airports" onClick={()=>setPass(p=>({...p,from:p.to,to:p.from}))}><ArrowLeftRight size={16}/></button><AirportSearch label="Arrival airport" value={pass.to} onChange={v=>update('to',v)} airports={airports}/></div><div className="two-fields"><Field label="Travel date" id="date" type="date" value={pass.date} required onChange={e=>update('date',e.target.value)}/><Field label="Boarding time" id="time" type="time" value={pass.boardingTime} required onChange={e=>update('boardingTime',e.target.value)}/></div><div className="four-fields"><Field label="Flight number" id="flight" value={pass.flight} maxLength={12} required onChange={e=>update('flight',e.target.value.toUpperCase())}/><Field label="Seat" id="seat" value={pass.seat} maxLength={6} required onChange={e=>update('seat',e.target.value.toUpperCase())}/><Field label="Gate" id="gate" value={pass.gate} maxLength={8} required onChange={e=>update('gate',e.target.value.toUpperCase())}/><Field label="Group" id="group" value={pass.group} maxLength={4} required onChange={e=>update('group',e.target.value)}/></div><div className="form-footer"><button type="button" onClick={reset}><RotateCcw size={13}/>Reset</button></div></form>}</div>
 <div className="export-strip"><button className="primary-button" disabled={!!busy} onClick={openExport}><Download size={16}/>{mode==='quick'&&batchCount>1?'Download boarding passes':'Download boarding pass'}</button>{provider==='free'&&<span className="quota-count" role="status" title="Shared site allowance. Resets at midnight UTC.">{quotaText}</span>}</div></section>
 <aside className="preview-panel"><div className="preview-heading"><div className="preview-tabs" role="group" aria-label="Preview side"><button className={!back?'active':''} aria-pressed={!back} onClick={()=>setBack(false)}>Front</button><button className={back?'active':''} aria-pressed={back} onClick={()=>setBack(true)}>Back</button></div></div><div className="preview-canvas"><PassPreview pass={previewPass} back={back}/></div><ColorPicker disabled={!!busy} value={previewPass.color||previewTemplate.color} defaultColor={previewTemplate.color} onChange={value=>mode==='quick'?setBatchColors(colors=>({...colors,[previewPass.template]:value})):update('color',value)}/></aside></div>
 </main></div>
 {notice&&<div className="toast" role="status"><Check size={17}/>{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss message"><X size={14}/></button></div>}
 {exportOpen&&<div className="modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setExportOpen(false);}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title" ref={exportRef}><button className="modal-close" disabled={!!busy} onClick={()=>setExportOpen(false)} aria-label="Close dialog"><X size={19}/></button><h2 id="dialog-title">{mode==='quick'&&batchCount>1?'Download boarding passes':'Download boarding pass'}</h2><p>{mode==='quick'?<>{batchName} · First class<br/>{batchCount} boarding {batchCount===1?'pass':'passes'}</>:<>{t.name} · {pass.from.code} → {pass.to.code}<br/>{pass.name} · {pass.cabin}</>}</p>{provider!=='unavailable'&&<div className="signing-state ready"><span/>{provider==='local'?'Signed with your certificate':quotaText}</div>}{provider==='free'&&<p className="modal-note">Shared site allowance. Resets at midnight UTC.</p>}{mode==='quick'?<><button disabled={!!busy||(batchCount>1&&batchFiles.length===batchCount)} className="primary-button full" onClick={downloadQuickBatch}>{busy==='batch'?<LoaderCircle size={17} className="spin"/>:<Wallet size={17}/>} {busy==='batch'?`Generating ${Math.min(batchProgress+1,batchCount)} of ${batchCount}…`:batchFiles.length===batchCount?(batchCount===1?'Download again':'Passes ready'):batchFiles.length?'Download remaining passes':batchCount===1?'Download boarding pass':'Download boarding passes'}</button><p className="modal-note">{batchCount} boarding {batchCount===1?'pass uses 1 generation':`passes use ${batchCount} generations`}.</p><PassDownloads files={batchFiles} passes={batchPasses}/></>:<><button disabled={!!busy} className="primary-button full" onClick={()=>download('pkpass')}>{busy==='pkpass'?<LoaderCircle size={17} className="spin"/>:<Wallet size={17}/>}Download .pkpass</button><div className="export-separator"><span>TEMPLATE BUNDLE</span></div><button className="outline-button full" disabled={!!busy} onClick={()=>download('zip')}>{busy==='zip'?<LoaderCircle size={17} className="spin"/>:<Download size={17}/>}Download template ZIP</button><details className="barcode-option"><summary>Use your own barcode text</summary><label htmlFor="barcode">Barcode payload</label><textarea id="barcode" maxLength={1000} disabled={!!busy} value={pass.barcode} onChange={e=>update('barcode',e.target.value)} placeholder="Paste an existing boarding pass barcode payload"/><small>Leave empty to generate a QR from your pass details.</small></details></>}{error&&<p className="error-message" role="alert">{error}</p>}</div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
